##**************************************************************************
##* Copyright (c) 2022, Advanced Micro Devices, Inc. All rights reserved.
##**************************************************************************

# Notes for compiling Frontier.
#
# We use the AMD programming environment and cray-mpich. Pease see compiling setion 
# https://docs.olcf.ornl.gov/systems/frontier_user_guide.html#compiling for more details
# on compiling on Frontier.

# Set the path to ROCm. For Frontier the environmental variable "ROCM_PATH" stores
# this path. We define a target my_rocm_path that tests if the ROCM_PATH is defined.
# If ROCM_PATH is not defined the we exit.
my_rocm_path:
ifndef ROCM_PATH
	@echo "ROCM_PATH environmnetal variable is undefined."
	exit 1
else
	@echo "ROCM_PATH environmnetal variable is defined to ${ROCM_PATH}"
endif

# ----------------------------------------------------------------------
# Define the installation directory of the binary.
# ----------------------------------------------------------------------
INSTALL_DIR=$(shell pwd)/bin

# ----------------------------------------------------------------------
# Define the HIP compiler.
# ----------------------------------------------------------------------
HIPCC=${ROCM_PATH}/bin/hipcc 

# ----------------------------------------------------------------------
# Define the HIP compiler flags. We use the hipconfig command
# to to get some of the options.
# ----------------------------------------------------------------------
HIP_CFLAGS=$(shell $(ROCM_PATH)/bin/hipconfig --cpp_config) \
           --offload-arch=gfx90a \
           -I$(ROCM_PATH)/roctracer/include -I${ROCM_PATH}/include/roctracer

# ----------------------------------------------------------------------
# Define the HIP linker flags.
# ----------------------------------------------------------------------
HIP_LDFLAGS=-L$(ROCM_PATH)/lib/ -lroctx64 -lroctracer64 -lamdhip64

# ----------------------------------------------------------------------
# Define some general C and C++ compilation flags.
# ----------------------------------------------------------------------
CFLAGS=-O3 -g -ggdb -fPIC -std=c++11 -march=native -Wall

# ----------------------------------------------------------------------
# Define some general C,C++ linker flags.
# ----------------------------------------------------------------------
LDFLAGS=

# ----------------------------------------------------------------------
# Define the MPI header compile flags.
# ----------------------------------------------------------------------
MPI_CFLAGS=-I${MPICH_DIR}/include

# ----------------------------------------------------------------------
# Define the MPI linking flags.
# ----------------------------------------------------------------------
MPI_LDFLAGS=-L${MPICH_DIR}/lib -lmpi \
    ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem \
    ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}

# ----------------------------------------------------------------------
# Define the linker.
# ----------------------------------------------------------------------
LINKER=${HIPCC}
