##**************************************************************************
##* Copyright (c) 2022, Advanced Micro Devices, Inc. All rights reserved.
##**************************************************************************

# Notes for compiling Frontier.
# 
# Frontier uses 'srun' instead of 'mpirun' to execute MPI programs.

# Set the path to rocm. For Frontier the environmental variable "ROCM_PATH" stores
# this path. We define a target my_rocm_path that tests if the ROCM_PATH is defined.
my_rocm_path:
ifndef ROCM_PATH
	@echo "ROCM_PATH environmnetal variable is undefined."
	exit 1
else
	@echo "ROCM_PATH environmnetal variable is defined to ${ROCM_PATH}"
endif

# Define the installation directory of the binary.
INSTALL_DIR=$(shell pwd)/bin

# Define the HIP compiler and compiler flags.
HIPCC=${ROCM_PATH}/bin/hipcc 

HIP_CFLAGS=-D__HIP_PLATFORM_HCC__ --offload-arch=gfx90a \
		-I$(ROCM_PATH)/roctracer/include -I${ROCM_PATH}/include/roctracer

HIP_LDFLAGS=-L$(ROCM_PATH)/lib/ -lroctx64 -lroctracer64

CFLAGS=-O3 -g -ggdb -fPIC -std=c++11 -march=native -Wall

LDFLAGS=

# Define the MPI header files, compile and linking flags.
MPI_CFLAGS=-I${MPICH_DIR}/include

MPI_LDFLAGS=-L${MPICH_DIR}/lib -lmpi \
    ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem \
    ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}

